title: Welcome to Zanue's Blog!!
description: Blogs for Computer Vision, Geometry and More...
baseurl: "" # the subpath of your site, e.g. /blog
url:  zanue.github.io # the base hostname & protocol for your site, e.g. http://example.com

# Author
author-name:    Zanue
author-image:   my_photo.png
author-job:     CVer
author-email:   SJTU19zzw@sjtu.edu.cn # Add your email for contant form.
author-twitter: Zanue5 # Add your twitter account
about-author:   I am a second-year PhD student in Shanghai Jiao Tong University. Keep learning everything.

# Social settings
social-twitter:   
social-facebook:
social-github:    Zanue
social-pinterest: 
social-instagram: 
social-youtube:
social-vk:   
social-linkedin:

# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Google Analytics
google-analytics: G-2EY0HSLSV2 # Add your identifier. For example UA-99631805-1

# Comment Section (Disqus)
disqus-identifier: mr-brown # Add your shortname for Disqus Comment. For example mr-brown

# Build settings
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/
plugins:
  - jekyll-paginate
  - jekyll-figure

paginate: 7
paginate_path: "/page/:num/"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
